"""청소 카테고리 시드 상품 — 웹 리서치 기반 후보 풀."""

from __future__ import annotations

from typing import Any

# affiliate_url은 운영자가 쿠팡파트너스 등으로 교체해야 함
CLEANING_PRODUCTS: list[dict[str, Any]] = [
    {
        "product_id": "P001",
        "product_name": "창틀 틈새 청소 브러시",
        "category": "청소",
        "source": "쿠팡/네이버쇼핑",
        "product_url": "https://www.coupang.com/np/search?q=창틀+틈새+청소+브러시",
        "affiliate_url": "",
        "price": 8900,
        "rating": 4.6,
        "review_count": 3200,
        "problem_statement": "창틀 틈새 먼지가 물티슈로 잘 안 닦임",
        "video_angle": "물티슈로 안 닦이는 창틀 틈새 해결",
        "before_scene": "물티슈로 창틀을 닦아도 먼지가 남는 장면",
        "after_scene": "브러시로 틈새 먼지를 밀어낸 뒤 깔끔해진 창틀",
        "known_downside": "오래 묵은 곰팡이는 세제와 함께 써야 함",
        "why_selected": "Before/After가 명확하고 가격이 낮음",
        "risk_notes": "곰팡이 완전 제거 표현 금지",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 5,
            "impulse_buy": 5,
            "review_trust": 4,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P002",
        "product_name": "디어커스 국산 처마형 싱크대 물막이",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=디어커스+처마+싱크대+물막이",
        "affiliate_url": "",
        "price": 15900,
        "rating": 4.9,
        "review_count": 2243,
        "problem_statement": "설거지할 때 싱크대 물이 바닥과 옷으로 튐",
        "video_angle": "물 튀는 설거지 스트레스 해결",
        "before_scene": "설거지 중 물이 싱크대 밖으로 튀는 장면",
        "after_scene": "처마형 물막이 설치 후 물이 싱크 안으로만 흐르는 장면",
        "known_downside": "싱크대 폭·높이에 맞는 규격 확인 필요",
        "why_selected": "리뷰 2200+ · 평점 4.9 · 문제 장면이 즉시 공감됨",
        "risk_notes": "곰팡이/물때 완전 방지 표현 금지",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 5,
            "impulse_buy": 4,
            "review_trust": 5,
            "price_fit": 4,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P003",
        "product_name": "욕실 물때 스크래퍼",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=욕실+물때+스크래퍼",
        "affiliate_url": "",
        "price": 9900,
        "rating": 4.5,
        "review_count": 1800,
        "problem_statement": "욕실 타일 물때가 손으로 닦기 힘듦",
        "video_angle": "욕실 물때 청소 귀찮으면 이거",
        "before_scene": "욕실 타일에 물때가 끼어 있는 장면",
        "after_scene": "스크래퍼로 긁은 뒤 비교되는 구역",
        "known_downside": "오래된 물때는 세제 병행 필요",
        "why_selected": "Before/After 대비가 크고 가격대 적합",
        "risk_notes": "물때 100% 제거 표현 금지",
        "ratings": {
            "problem_strength": 4,
            "video_ease": 5,
            "impulse_buy": 5,
            "review_trust": 4,
            "price_fit": 5,
            "claim_risk": 3,
        },
    },
    {
        "product_id": "P004",
        "product_name": "방충망 청소 롤러/브러시",
        "category": "청소",
        "source": "11번가/쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=방충망+청소+브러시",
        "affiliate_url": "",
        "price": 7900,
        "rating": 4.4,
        "review_count": 950,
        "problem_statement": "방충망 먼지가 손으로 닦기 불편함",
        "video_angle": "방충망 청소 손 안 더럽히는 방법",
        "before_scene": "먼지 쌓인 방충망 클로즈업",
        "after_scene": "롤러/브러시로 청소 후 비교",
        "known_downside": "틈새 깊은 먼지는 추가 도구 필요",
        "why_selected": "문제 인식 강하고 영상화 쉬움",
        "risk_notes": "알레르기/미세먼지 완전 제거 표현 금지",
        "ratings": {
            "problem_strength": 4,
            "video_ease": 5,
            "impulse_buy": 5,
            "review_trust": 3,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P005",
        "product_name": "전동 솔 창틀/틈새 청소기",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=전동+틈새+청소기",
        "affiliate_url": "",
        "price": 24900,
        "rating": 4.3,
        "review_count": 620,
        "problem_statement": "창틀·키보드·차량 틈새 먼지 제거가 번거로움",
        "video_angle": "손 청소 vs 전동 솔 비교",
        "before_scene": "틈새에 쌓인 먼지",
        "after_scene": "전동 솔로 빨아들인 뒤 깨끗해진 틈새",
        "known_downside": "배터리·흡입력은 제품마다 편차 있음",
        "why_selected": "비교 영상 소재가 강함",
        "risk_notes": "고가(2만원대) · 흡입력 과장 금지",
        "ratings": {
            "problem_strength": 4,
            "video_ease": 5,
            "impulse_buy": 3,
            "review_trust": 3,
            "price_fit": 3,
            "claim_risk": 3,
        },
    },
    {
        "product_id": "P006",
        "product_name": "쓰레기통 냄새 차단 뚜껑",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=음식물+쓰레기+냄새+차단",
        "affiliate_url": "",
        "price": 12900,
        "rating": 4.5,
        "review_count": 1100,
        "problem_statement": "음식물 쓰레기통 냄새가 주방에 퍼짐",
        "video_angle": "냄새 나는 쓰레기통 스트레스",
        "before_scene": "뚜껑 열 때 불쾌한 상황(과장 없이)",
        "after_scene": "밀폐 뚜껑 사용 후 주방 분위기",
        "known_downside": "통 규격 호환 확인 필요",
        "why_selected": "공감도 높고 설치 장면이 짧음",
        "risk_notes": "냄새 완전 차단 표현 금지",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 4,
            "impulse_buy": 4,
            "review_trust": 4,
            "price_fit": 4,
            "claim_risk": 3,
        },
    },
    {
        "product_id": "P007",
        "product_name": "세탁조 클리너 15회분",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=세탁조+클리너",
        "affiliate_url": "",
        "price": 11900,
        "rating": 4.7,
        "review_count": 8500,
        "problem_statement": "세탁조 찌든 때·냄새가 옷에 배는 느낌",
        "video_angle": "세탁조 청소 미루는 사람에게",
        "before_scene": "세탁조 러버링/거품 전 더러운 상태",
        "after_scene": "클리너 사용 후 거품·물 배출 장면",
        "known_downside": "찌든 때가 심하면 2회 사용 필요",
        "why_selected": "리뷰 많고 Before/After 명확",
        "risk_notes": "살균·세균 표현 금지 · 효과 과장 주의",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 4,
            "impulse_buy": 4,
            "review_trust": 5,
            "price_fit": 4,
            "claim_risk": 4,
        },
    },
    {
        "product_id": "P008",
        "product_name": "틈새 먼지 청소 솔(일회용)",
        "category": "청소",
        "source": "다이소/쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=틈새+먼지+청소+솔",
        "affiliate_url": "",
        "price": 4500,
        "rating": 4.2,
        "review_count": 2100,
        "problem_statement": "가구·창틀·키보드 틈새 먼지",
        "video_angle": "천 원대로 틈새 먼지 한 번에",
        "before_scene": "솔 넣기 전 틈새 먼지",
        "after_scene": "솔에 붙은 먼지 클로즈업",
        "known_downside": "일회용이라 반복 구매 필요",
        "why_selected": "초저가·충동구매·영상 짧게 가능",
        "risk_notes": "너무 흔한 바이럴템 — 각도 차별화 필요",
        "ratings": {
            "problem_strength": 4,
            "video_ease": 5,
            "impulse_buy": 5,
            "review_trust": 4,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P009",
        "product_name": "배수구 청소 집게/후크",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=배수구+청소+집게",
        "affiliate_url": "",
        "price": 5900,
        "rating": 4.4,
        "review_count": 3400,
        "problem_statement": "욕실·싱크 배수구 머리카락·이물질 제거",
        "video_angle": "배수구 막힘 예방",
        "before_scene": "배수구에 머리카락 끼인 장면",
        "after_scene": "집게로 끄집어낸 뒤 물 잘 빠지는 장면",
        "known_downside": "역한 장면 과도 노출은 시청 이탈 유발",
        "why_selected": "문제 강함 · 리뷰 많음",
        "risk_notes": "혐오 장면 과도 연출 금지",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 4,
            "impulse_buy": 5,
            "review_trust": 4,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P010",
        "product_name": "유리창 스퀴지 미니",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=미니+스퀴지+유리",
        "affiliate_url": "",
        "price": 6900,
        "rating": 4.3,
        "review_count": 780,
        "problem_statement": "욕실 거울·샤워부스 물자국",
        "video_angle": "샤워 후 거울 물자국 한 번에",
        "before_scene": "물자국 번진 거울",
        "after_scene": "스퀴지 후 맑아진 거울",
        "known_downside": "큰 창문에는 사이즈 부족",
        "why_selected": "Before/After 짧고 선명",
        "risk_notes": "무 streak 표현 금지",
        "ratings": {
            "problem_strength": 4,
            "video_ease": 5,
            "impulse_buy": 5,
            "review_trust": 3,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P011",
        "product_name": "반려동물 털 제거 롤러",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=반려동물+털+제거+롤러",
        "affiliate_url": "",
        "price": 8900,
        "rating": 4.6,
        "review_count": 5200,
        "problem_statement": "소파·카펫에 붙은 반려동물 털",
        "video_angle": "털 날리는 집 청소 팁",
        "before_scene": "털 붙은 소파 클로즈업",
        "after_scene": "롤러로 제거 후 비교",
        "known_downside": "짧은 털·정전기 털은 한계",
        "why_selected": "반려 가구 타깃 · 리뷰 풍부",
        "risk_notes": "100% 털 제거 표현 금지",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 5,
            "impulse_buy": 5,
            "review_trust": 5,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P012",
        "product_name": "HUTT 창문 로봇청소기",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=HUTT+창문+로봇청소기",
        "affiliate_url": "",
        "price": 189000,
        "rating": 4.5,
        "review_count": 890,
        "problem_statement": "바깥창·고층 창문 청소 어려움",
        "video_angle": "로봇이 창문 닦는 장면",
        "before_scene": "더러운 통창",
        "after_scene": "로봇 작동 후 창문",
        "known_downside": "고가 · 유리 두께 제한",
        "why_selected": "영상은 화려하나 가격·규제 리스크",
        "risk_notes": "고가 가전 — 초기 제외 카테고리",
        "regulatory_risk": False,
        "ratings": {
            "problem_strength": 4,
            "video_ease": 5,
            "impulse_buy": 1,
            "review_trust": 4,
            "price_fit": 1,
            "claim_risk": 3,
        },
    },
    {
        "product_id": "P013",
        "product_name": "가스레인지 틈새 청소 브러시",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=가스레인지+틈새+청소",
        "affiliate_url": "",
        "price": 5500,
        "rating": 4.4,
        "review_count": 1400,
        "problem_statement": "가스레인지 틈새 기름때·음식물 찌꺼기",
        "video_angle": "주방 청소에서 제일 귀찮은 틈새",
        "before_scene": "레인지 틈새 기름때",
        "after_scene": "브러시로 꺼낸 후",
        "known_downside": "눌어붙은 때는 세제 필요",
        "why_selected": "주방+청소 교차 · 저가",
        "risk_notes": "기름때 완전 제거 표현 금지",
        "ratings": {
            "problem_strength": 5,
            "video_ease": 4,
            "impulse_buy": 5,
            "review_trust": 4,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
    {
        "product_id": "P014",
        "product_name": "전자레인지 내부 청소 스팀 클리너",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=전자레인지+스팀+청소",
        "affiliate_url": "",
        "price": 7900,
        "rating": 4.1,
        "review_count": 890,
        "problem_statement": "전자레인지 내부 기름때·냄새",
        "video_angle": "전자레인지 청소 귀찮은 사람",
        "before_scene": "내부 때 끼인 전자레인지",
        "after_scene": "스팀 후 닦아낸 내부",
        "known_downside": "심한 때는 추가 닦기 필요",
        "why_selected": "짧은 사용 장면 · 공감도 좋음",
        "risk_notes": "살균·냄새 완전 제거 표현 금지",
        "ratings": {
            "problem_strength": 4,
            "video_ease": 4,
            "impulse_buy": 5,
            "review_trust": 3,
            "price_fit": 5,
            "claim_risk": 3,
        },
    },
    {
        "product_id": "P015",
        "product_name": "먼지떨이 정전기 청소패",
        "category": "청소",
        "source": "쿠팡",
        "product_url": "https://www.coupang.com/np/search?q=정전기+먼지떨이",
        "affiliate_url": "",
        "price": 9900,
        "rating": 4.3,
        "review_count": 670,
        "problem_statement": "선반·가전 위 먼지가 자주 쌓임",
        "video_angle": "먼지떨이 vs 정전기 패 비교",
        "before_scene": "먼지 쌓인 선반",
        "after_scene": "패로 닦은 후",
        "known_downside": "패 교체 주기 필요",
        "why_selected": "비교 영상 소재",
        "risk_notes": "미세먼지 완전 제거 표현 금지",
        "ratings": {
            "problem_strength": 3,
            "video_ease": 4,
            "impulse_buy": 4,
            "review_trust": 3,
            "price_fit": 5,
            "claim_risk": 2,
        },
    },
]
